### ISSUE TITLE
Developer cannot init ERROR:ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by gokberkyar** [GYRY-NEU/CS7610#2] opened 2021-12-02 04:47 UTC
-  Error State

- Coordinator listens works at ~/Simulation/TempCoordinator/  as Linux 43.
- Workers linux both 42 (45) are registered. they work at ~/Simulation/TempWorker/Worker_42(45).
- Developer completed setup phase as Linux 46. Runs at ~/Simulation/TempDeveloper/Developer_46. Upload model is called.
- Coordinator as a copy of the zip file
- Developer curls the master with init command.
Expected Behavior.

- Model is copied to workers and runs successfully and returns appropriate responses for getModel and getRound.

BUG:
ModuleNotFoundError: No module named 'main' 

How to reproduce

- clone repo ssh linux40
- follow readme for getstarted
- ssh linux46 new tab
- cd /home/yarg/Simulation/TempDeveloper/TempDeveloper_046
- export funcID='copy from the linux 40 terminal'
- curl --resolve $funcId:10000:10.200.125.43 http://$funcId:10000/init

**Comment by hare1039** [comment] 2021-12-04 01:38
Not a bug in this repo,
Fixed by https://github.com/GYRY-NEU/Simulation/commit/7ae56eef145b7bad146f5ba4251ad1bae0d01be2

**Closed as completed by hare1039** 2021-12-04 01:38 UTC
Labels: bug
